Adding Hive to Runtime spec
odpi/specs pull request #44
Opened 2016-08-26 19:24 UTC by alanfgates

Here's an initial PR for people to review.  This adds Hive to the runtime spec.

2016-09-06 20:37 UTC, rajddesai commented
+1

2016-09-14 19:52 UTC, jmertic commented on ODPi-Runtime.md
> +ODPi Runtime Specification: 1.1
This should be 2.0.

2016-09-14 19:53 UTC, jmertic commented on ODPi-Runtime.md
> +-   Applications SHOULD use JDBC, ODBC, or SQL to determine the structure of metadata rather than directly querying the metastore thrift interface whenever possible.
Is it understood enough that this would be via Hive, or should that be called out?

2016-09-14 19:54 UTC, jmertic commented on ODPi-Runtime.md
> +To help achieve TONE, ODPi-compliant platforms MUST conform to the following build specifications.
Proper terminology should be 'ODPi Runtime Compliant Platforms'

2016-09-14 19:55 UTC, jmertic requested changes
Small cleanups needed.

2016-09-14 23:41 UTC, alanfgates commented on ODPi-Runtime.md
> +To help achieve TONE, ODPi-compliant platforms MUST conform to the following build specifications.
ODPI-compliant is used all over this section of the spec.  If we want to change that we should have a separate issue to change them all.

2016-09-14 23:46 UTC, alanfgates commented
Changed version number and made it clear we're talking about Hive metadata, per John's feedback.  Rejected last comment on ODPi-compliant as that is used extensively, not just in that one place.

2016-09-15 12:31 UTC, jmertic approved these changes

2016-09-21 22:26 UTC, rvs commented
LGTM. Lets merge!

2016-09-22 16:29 UTC, merged