Merging HCFS into the body of ODPi-Runtime document
odpi/specs pull request #59
Opened 2016-10-17 00:07 UTC by rvs

2016-10-17 19:25 UTC, mattf-apache requested changes
Overall good job of integration.  Some edits are recommended, please see individual notes.

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +ODPi Platforms MAY include alternative filesystem implementations compatible with Apache Hadoop (HCFS). HCFS implementations MAY be delivered as standalone products by either ODPi Platform vendors or
1. Need to distinguish between the filesystem itself, which certainly may be delivered as a standalone product, and the HCFS implementation JAR, which in the next paragraph you require to be integrated into the ODPi Platform as shipped.  Suggest a change of terminology: Use the term "HCFS Filesystem Product" to refer to underlying filesystem implementation that may be delivered by a third party; and use the term "HCFS Interface JAR" in place of the former "HCFS implementation JAR".  Thus the above paragraph would read: 
   - "ODPi Platforms MAY include alternative filesystem implementations compatible with Apache Hadoop (HCFS). Such HCFS Filesystem Products MAY be delivered as standalone products by either ODPi Platform vendors or 3d parties. These products MAY be open source or they MAY be proprietary. Regardless of the delivery mechanism, ODPi Platform vendors have the ultimate responsibility around integrating HCFS Filesystem Products with the rest of the ODPi platform by following the guidelines provided below:"
2. ODPI Platform vendors have such responsibility only for HCFS Filesystem Products that they _support_ (not those delivered by arbitrary 3rd parties).  Perhaps add the word "supported" to the last sentence:
   - "ODPi Platform vendors have the ultimate responsibility around integrating supported HCFS Filesystem Products with the rest of the ODPi platform by following the guidelines provided below:"

BTW, I don't particularly agree with the statement, even with that addition; it seems to me the 3rd parties if any should be responsible.  Do the ODPI Platform vendors accept this responsibility?

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +- ODPi Platform MUST ship HCFS implementation JAR as part of the ODPi Platform. HCFS implementation JAR is a compiled Java JAR that provides the interface, or “glue layer” between the HCFS implementa
1. As noted above, please replace all instances throughout the text:
   - "HCFS implementation JAR" --> "HCFS Interface JAR"
   - then "HCFS implementation" --> "HCFS Filesystem Product"
2. The requirements for the classes shipped as part of HCFS Interface JAR are specified by the Apache Hadoop documentation, and summarized in the guidelines below. (Not specified in this document as implied by current text.)

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +- ODPi Platform MUST define a scheme name for all HCFS implementation that they ship. A scheme name is a unique, one-word name for each file system. A scheme name is used in the URI “scheme:” prefix,
"scheme name for all HCFS implementations" -> "scheme name for each HCFS Filesystem Product"

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +   * `s3a` (Amazon)
`s3a`, `s3native` (Amazon S3)

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +   * `wasb` (Windows Azure)
`wasb`, `adl` (Microsoft Azure)

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +- ODPi Platforms SHOULD be compatible with POSIX ACL and POSIX permissions. It is recommended that HCFS implementations follow HDFS in how they treat group ID for the newly created files: inhereting
inhereting --> inheriting

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +- Applications SHOULD define APIs and behaviors explicitly in the FileSystem class instead of the HDFS class. A file system will be HCFS compatible if all the APIs are implemented from the FileSystem
Perhaps I misunderstand, but I think the desired meaning here should be stated:
- Applications SHOULD invoke filesystem client APIs and behaviors explicitly from the FileSystem and FileContext classes instead of the HDFS class. A file system will be HCFS compatible if all the APIs are implemented from the FileSystem class and AbstractFileSystem class (the latter is used by the FileContext client APIs).  Implementing API specifications from the HDFS class is considered optional usage in HCFS Interface JAR.

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +ODPi Platform providers MAY include results of compliance testing with HCFS implementations in the submission presented to ODPi. These results MUST at least include execution of tests created in acco
"include results of compliance testing with HCFS implementations" --> "include results of compliance testing with supported HCFS implementations"

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +#### HCFS implementation guidelines
Here I would use "HCFS Interface implementation guidelines"

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +HCFS implementations MUST follow the guidelines laid out in the Hadoop FileSystem API Definition available as part of Apache Hadoop release and also available [*online*](https://hadoop.apache.org/doc
Again, "HCFS implementations" --> "HCFS Interface implementation guidelines"

2016-10-17 19:25 UTC, mattf-apache commented on ODPi-Runtime.md
> +package `org.apache.hadoop.fs.<hcfsname>`.  It SHOULD NOT be named in the `META-INF/services` file.
It MUST NOT be named in the `META-INF/services` file.

2016-10-17 19:25 UTC, mattf-horton commented on ODPi-Runtime.md
> +implementation provides a drop-in replacement for HDFS it MUST support all of the ODPi Core components without degradation in
Regarding the last sentence ("Regardless of whether..."), must distinguish between HCFS supported by the ODPi Platform vendor for substitution in place of HDFS, vs HCFS supported only for use via generic input/output.  Some core components, including MapReduce, Tez and HBase, will not be fully supported by the latter.  Suggest the phrasing:
* If an ODPi Platform supports an HCFS Filesystem Product as a drop-in replacement for HDFS, then it MUST support all of the ODPi Core components without degradation in functionality.  If an ODPi Platform supports an HCFS Filesystem Product only for use with Application input/output, then it must support Applications' use of FileContext APIs without degradation in functionality.

2016-10-17 19:25 UTC, mattf-horton commented on ODPi-Runtime.md
> +```
Nice example.

2016-10-17 19:30 UTC, mattf-horton commented
BTW, are you going to integrate the Ambari-related portions of the original draft document (HCFS-Installation.md, deleted in toto above) into the ODPi-Operations document?

2016-10-18 18:17 UTC, rvs commented
Thanks for the kind words -- you did all the hard work, by the way. Also thanks for awesome review -- I going over your comments now. An update to this PR should be out shortly today.

2016-10-18 18:22 UTC, rvs commented on ODPi-Runtime.md
> +ODPi Platforms MAY include alternative filesystem implementations compatible with Apache Hadoop (HCFS). HCFS implementations MAY be delivered as standalone products by either ODPi Platform vendors or
Great comments on the wording. I updated the document. As to your question of whether ODPi Platform vendors have agreed -- the answer is "yes". This was, in fact, an outcome of two pretty long discussions. For now we only allow ODPi compatibility mark to ODPi Platform vendors and what gets certified is a whole platform. Which means that any 3d party seeking certification will have to go through a Platform Vendor. IOW, GPFS can't be currently certified, but IBM BigInsights (including GPFS) can be.

2016-10-18 18:29 UTC, rvs commented on ODPi-Runtime.md
> +- ODPi Platform MUST ship HCFS implementation JAR as part of the ODPi Platform. HCFS implementation JAR is a compiled Java JAR that provides the interface, or “glue layer” between the HCFS implementa
Fixed.

2016-10-18 18:31 UTC, rvs commented on ODPi-Runtime.md
> +- ODPi Platform MUST define a scheme name for all HCFS implementation that they ship. A scheme name is a unique, one-word name for each file system. A scheme name is used in the URI “scheme:” prefix,
Fixed.

2016-10-18 18:32 UTC, rvs commented on ODPi-Runtime.md
> +   * `s3a` (Amazon)
Fixed.

2016-10-18 18:32 UTC, rvs commented on ODPi-Runtime.md
> +   * `wasb` (Windows Azure)
Fixed.

2016-10-18 18:35 UTC, rvs commented on ODPi-Runtime.md
> +- ODPi Platforms SHOULD be compatible with POSIX ACL and POSIX permissions. It is recommended that HCFS implementations follow HDFS in how they treat group ID for the newly created files: inhereting
Good catch!

2016-10-18 18:37 UTC, rvs commented on ODPi-Runtime.md
> +- Applications SHOULD define APIs and behaviors explicitly in the FileSystem class instead of the HDFS class. A file system will be HCFS compatible if all the APIs are implemented from the FileSystem
Fixed.

2016-10-18 18:38 UTC, rvs commented on ODPi-Runtime.md
> +ODPi Platform providers MAY include results of compliance testing with HCFS implementations in the submission presented to ODPi. These results MUST at least include execution of tests created in acco
Fixed.

2016-10-18 18:38 UTC, rvs commented on ODPi-Runtime.md
> +#### HCFS implementation guidelines
Fixed.

2016-10-18 18:42 UTC, rvs commented on ODPi-Runtime.md
> +HCFS implementations MUST follow the guidelines laid out in the Hadoop FileSystem API Definition available as part of Apache Hadoop release and also available [*online*](https://hadoop.apache.org/doc
Fixed.

2016-10-18 18:42 UTC, rvs commented on ODPi-Runtime.md
> +package `org.apache.hadoop.fs.<hcfsname>`.  It SHOULD NOT be named in the `META-INF/services` file.
Fixed.

2016-10-18 18:47 UTC, rvs commented on ODPi-Runtime.md
> +implementation provides a drop-in replacement for HDFS it MUST support all of the ODPi Core components without degradation in
Makes perfect sense!

2016-10-18 19:44 UTC, mattf-apache approved these changes
+1, looks good Roman!

2016-10-19 23:49 UTC, merged